name: escli
version: 0.0.1
description: The complete solution for dart command-line interfaces.
authors:
  - axetroy <troy450409405@gmail.com>
homepage: https://github.com/axetroy/command

dependencies:
  ee: ">=0.0.1 <= 1.0.0"

dev_dependencies:
  test: