name: command
version: 0.0.1
description: The complete solution for dart command-line interfaces.
author:
  - axetroy <troy450409405@gmail.com>
homepage: https://github.com/axetroy/command

dev_dependencies:
  test: